# Generated by Django 2.0.3 on 2018-03-16 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxsign', '0002_otp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Otp',
            new_name='Otp_check',
        ),
    ]
