# Generated by Django 2.0.3 on 2018-03-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxsign', '0003_auto_20180316_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp_check',
            name='status',
        ),
    ]
