# Generated by Django 2.0.3 on 2018-03-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxsign', '0004_remove_otp_check_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp_check',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
