# Generated by Django 2.0.3 on 2018-03-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxsign', '0007_auto_20180316_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='home/sony/python/django/signup/media/'),
        ),
    ]
