# Generated by Django 2.0.3 on 2018-03-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxsign', '0008_auto_20180317_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
