# Generated by Django 2.0.3 on 2018-03-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajaxsign', '0010_auto_20180318_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='contact',
            field=models.IntegerField(default=0),
        ),
    ]
